_target_: nlhappy.datamodules.EntityExtractionDataModule
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}


dataset: 
batch_size: 
transform: w2
plm: hfl/chinese-roberta-wwm-ext
auto_length: max
pin_memory: False
num_workers: 0