_target_: nlhappy.datamodules.SpanClassificationDataModule
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}


dataset: 
max_length: 
batch_size: 
plm: chinese-roberta-wwm-ext
pin_memory: False
num_workers: 0

