_target_: nlhappy.datamodules.TextClassificationDataModule
dataset_dir: ${dataset_dir} 
plm_dir: ${plm_dir}

dataset: 
batch_size: 
plm: roberta-wwm-ext
transform: simple
auto_length: max
num_workers: 0
pin_memory: False


